projects/OYD-Daily/OYD_Daily_App/config/routes.rb
Rails.application.routes.draw do
  resources :mlt_attendances
  resources :tests
  resources :information
  get 'sessions/new'

  resources :attendances
  resources :schools
  resources :students
  resources :users
  resources :sessions
  resources :informations
  resources :tests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#new'
  get 'user/:id/select_school', to: "users#select_school", as: 'select_school'
  get 'user/:id/select_date', to: "users#select_date", as: 'select_date'
  get 'school/:id/mark_attendance', to: "schools#mark_attendance", as: 'mark_attendances'
  get 'school/:id/register_student', to: "schools#register_student", as: 'register_student'
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as =>"log_out"
  get 'school/:id/add_information', to: "schools#add_information", as: 'add_information'
  
end

projects/OYD-Daily/OYD_Daily_App/app/models/mlt_attendance.rb
class MltAttendance < ApplicationRecord
  belongs_to :student
end

projects/OYD-Daily/OYD_Daily_App/app/controllers/mlt_attendances_controller.rb
class MltAttendancesController < ApplicationController
  before_action :set_mlt_attendance, only: [:show, :edit, :update, :destroy]

  # GET /mlt_attendances
  # GET /mlt_attendances.json
  def index
    @mlt_attendances = MltAttendance.all
  end

  # GET /mlt_attendances/1
  # GET /mlt_attendances/1.json
  def show
  end

  # GET /mlt_attendances/new
  def new
    @mlt_attendance = MltAttendance.new
    @school = School.find(params[:school])
    @students = @school.students
    @date = params[:date].to_date
  end

  # GET /mlt_attendances/1/edit
  def edit
  end

  # POST /mlt_attendances
  # POST /mlt_attendances.json
  def create
    @mlt_attendance = MltAttendance.new(mlt_attendance_params)

    respond_to do |format|
      if @mlt_attendance.save
        format.html { redirect_to @mlt_attendance, notice: 'Mlt attendance was successfully created.' }
        format.json { render :show, status: :created, location: @mlt_attendance }
      else
        format.html { render :new }
        format.json { render json: @mlt_attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mlt_attendances/1
  # PATCH/PUT /mlt_attendances/1.json
  def update
    respond_to do |format|
      if @mlt_attendance.update(mlt_attendance_params)
        format.html { redirect_to @mlt_attendance, notice: 'Mlt attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @mlt_attendance }
      else
        format.html { render :edit }
        format.json { render json: @mlt_attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mlt_attendances/1
  # DELETE /mlt_attendances/1.json
  def destroy
    @mlt_attendance.destroy
    respond_to do |format|
      format.html { redirect_to mlt_attendances_url, notice: 'Mlt attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mlt_attendance
      @mlt_attendance = MltAttendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mlt_attendance_params
      params.require(:mlt_attendance).permit(:student_id, :mlt_date, :course, :lesson)
    end
end

projects/OYD-Daily/OYD_Daily_App/app/helpers/mlt_attendances_helper.rb
module MltAttendancesHelper
end

projects/OYD-Daily/OYD_Daily_App/app/views/mlt_attendances/_form.html.erb
<%= form_with(model: mlt_attendance, local: true) do |form| %>
  <% if mlt_attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mlt_attendance.errors.count, "error") %> prohibited this mlt_attendance from being saved:</h2>

      <ul>
      <% mlt_attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.collection_select :student_id, @students, :id, :full_name, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :mlt_date %>
    <%= form.date_select :mlt_date, id: :mlt_attendance_mlt_date %>
  </div>

  <div class="field">
    <%= form.label :course %>
    <%= form.number_field :course, id: :mlt_attendance_course %>
  </div>

  <div class="field">
    <%= form.label :lesson %>
    <%= form.number_field :lesson, id: :mlt_attendance_lesson %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

projects/OYD-Daily/OYD_Daily_App/app/views/mlt_attendances/edit.html.erb
<h1>Editing Mlt Attendance</h1>

<%= render 'form', mlt_attendance: @mlt_attendance %>

<%= link_to 'Show', @mlt_attendance %> |
<%= link_to 'Back', mlt_attendances_path %>

projects/OYD-Daily/OYD_Daily_App/app/views/mlt_attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mlt Attendances</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Mlt date</th>
      <th>Course</th>
      <th>Lesson</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mlt_attendances.each do |mlt_attendance| %>
      <tr>
        <td><%= mlt_attendance.student %></td>
        <td><%= mlt_attendance.mlt_date %></td>
        <td><%= mlt_attendance.course %></td>
        <td><%= mlt_attendance.lesson %></td>
        <td><%= link_to 'Show', mlt_attendance %></td>
        <td><%= link_to 'Edit', edit_mlt_attendance_path(mlt_attendance) %></td>
        <td><%= link_to 'Destroy', mlt_attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mlt Attendance', new_mlt_attendance_path %>

projects/OYD-Daily/OYD_Daily_App/app/views/mlt_attendances/new.html.erb
<h1>New Mlt Attendance</h1>

<%= render 'form', mlt_attendance: @mlt_attendance %>

<%= link_to 'Back', mlt_attendances_path %>

projects/OYD-Daily/OYD_Daily_App/app/views/mlt_attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @mlt_attendance.student %>
</p>

<p>
  <strong>Mlt date:</strong>
  <%= @mlt_attendance.mlt_date %>
</p>

<p>
  <strong>Course:</strong>
  <%= @mlt_attendance.course %>
</p>

<p>
  <strong>Lesson:</strong>
  <%= @mlt_attendance.lesson %>
</p>

<%= link_to 'Edit', edit_mlt_attendance_path(@mlt_attendance) %> |
<%= link_to 'Back', mlt_attendances_path %>