projects/OYD-Daily/OYD_Daily_App/config/routes.rb
Rails.application.routes.draw do
  resources :mlt_attendances
  resources :tests
  resources :information
  get 'sessions/new'

  resources :attendances
  resources :schools
  resources :students
  resources :users
  resources :sessions
  resources :informations
  resources :tests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#new'
  get 'user/:id/select_school', to: "users#select_school", as: 'select_school'
  get 'user/:id/select_date', to: "users#select_date", as: 'select_date'
  get 'school/:id/mark_attendance', to: "schools#mark_attendance", as: 'mark_attendances'
  get 'school/:id/register_student', to: "schools#register_student", as: 'register_student'
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as =>"log_out"
  get 'school/:id/add_information', to: "schools#add_information", as: 'add_information'
  
end

projects/OYD-Daily/OYD_Daily_App/app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :student
end

projects/OYD-Daily/OYD_Daily_App/app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_params
      params.require(:attendance).permit(:student_id, :when)
    end
end

projects/OYD-Daily/OYD_Daily_App/app/helpers/attendances_helper.rb
module AttendancesHelper
end

projects/OYD-Daily/OYD_Daily_App/app/views/attendances/_form.html.erb
<%= form_with(model: attendance, local: true) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.collection_select :student_id, Student.order(:first_name), :id, :first_name, include_blank: true %>
    <%# form.text_field :student_id, id: :attendance_student_id %>
  </div>

  <div class="field">
    <%= form.label :when %>
    <%= form.datetime_select :when, id: :attendance_when %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

projects/OYD-Daily/OYD_Daily_App/app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

projects/OYD-Daily/OYD_Daily_App/app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>When</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.student.first_name %></td>
        <td><%= attendance.when %></td>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
        <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>

projects/OYD-Daily/OYD_Daily_App/app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

projects/OYD-Daily/OYD_Daily_App/app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @attendance.student %>
</p>

<p>
  <strong>When:</strong>
  <%= @attendance.when %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>