projects/OYD-Daily/OYD_Daily_App/config/routes.rb
Rails.application.routes.draw do
  resources :mlt_attendances
  resources :tests
  resources :information
  get 'sessions/new'

  resources :attendances
  resources :schools
  resources :students
  resources :users
  resources :sessions
  resources :informations
  resources :tests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#new'
  get 'user/:id/select_school', to: "users#select_school", as: 'select_school'
  get 'user/:id/select_date', to: "users#select_date", as: 'select_date'
  get 'school/:id/mark_attendance', to: "schools#mark_attendance", as: 'mark_attendances'
  get 'school/:id/register_student', to: "schools#register_student", as: 'register_student'
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as =>"log_out"
  get 'school/:id/add_information', to: "schools#add_information", as: 'add_information'
  
end

projects/OYD-Daily/OYD_Daily_App/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
  	user = find_by_email(email)
  	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    		user
    	end
  end

end

projects/OYD-Daily/OYD_Daily_App/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, :require_login, only: [:show, :edit, :update, :destroy, :select_school, :select_date]
  protect_from_forgery except: [:select_school, :select_date]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

    @schools = School.all
    if params[:prev_date].nil?
      params[:start_date] = Date.today
    else
      params[:start_date] = params[:prev_date]
    end
    if params[:selected].nil?
      @selected = @schools.first
    else
      @selected = @schools.find(params[:selected])
    end
    params[:selected] = @selected.id
    @students = Student.where(school_id: @selected.id)
    student_ids = []
    @students.each do |s|
      student_ids << s.id
    end
    @attendance = Attendance.where(when: params[:start_date].to_date.beginning_of_month .. params[:start_date].to_date.end_of_month, student_id: student_ids)
    #@attendance.each do |a|
    #  logger.debug a.when
    #end
    #logger.debug "did it"
  end

  def select_school
    @schools = School.all
    @selected = School.find(params[:selected])
    params[:start_date] = params[:prev_date]
    logger.debug "=========="
    logger.debug params[:start_date]
    logger.debug "=========="
    #@attendance = Attendance.where(when: Date.today.beginning_of_month .. Date.today.end_of_month)
    @students = Student.where(school_id: @selected.id)
    student_ids = []
    @students.each do |s|
      student_ids << s.id
    end
    @attendance = Attendance.where(when: params[:prev_date].to_date.beginning_of_month .. params[:prev_date].to_date.end_of_month, student_id: student_ids)
    respond_to do |format|
      format.js 
    end
  end

  def select_date
    @schools = School.all
    @selected = School.find(params[:selected])
    #@attendance = Attendance.where(when: Date.today.beginning_of_month .. Date.today.end_of_month)

    @students = Student.where(school_id: @selected.id)
    student_ids = []
    @students.each do |s|
      student_ids << s.id
    end
    


    if params[:dir] == "forward" 
      params[:start_date] = params[:prev_date].to_date.next_month
    elsif params[:dir] == "backward"
      params[:start_date] = params[:prev_date].to_date.prev_month
    end

    @attendance = Attendance.where(when: params[:start_date].beginning_of_month .. params[:start_date].end_of_month, student_id: student_ids)

    respond_to do |format|
      format.js 
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    # NOTE - correct for interns etc. (no titles)
    @user.username = user_params["title"].downcase + '_' + user_params["first_name"].downcase

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :oyd_id, :access_level, :first_name, :last_name, :def_school, :def_region, :def_nat_area, :auth_schools, :title, :email, :password, :password_confirmation)
    end
end

projects/OYD-Daily/OYD_Daily_App/app/helpers/users_helper.rb
module UsersHelper
end

projects/OYD-Daily/OYD_Daily_App/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_area :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_area :last_name, id: :user_last_name %>
  </div>

 <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :user_title %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_area :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :oyd_id %>
    <%= form.number_field :oyd_id, id: :user_oyd_id %>
  </div>

  <div class="field">
    <%= form.label :access_level %>
    <%= form.number_field :access_level, id: :user_access_level %>
  </div>



  <div class="field">
    <%= form.label :def_school %>
    <%= form.text_area :def_school, id: :user_def_school %>
  </div>

  <div class="field">
    <%= form.label :def_region %>
    <%= form.text_area :def_region, id: :user_def_region %>
  </div>

  <div class="field">
    <%= form.label :def_nat_area %>
    <%= form.text_area :def_nat_area, id: :user_def_nat_area %>
  </div>

  <div class="field">
    <%= form.label :auth_schools %>
    <%= form.text_area :auth_schools, id: :user_auth_schools %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

projects/OYD-Daily/OYD_Daily_App/app/views/users/_month_data.html.erb
  <div id="prev-month-button">
  <%= link_to '<i class="angle left icon"></i>'.html_safe, select_date_path(@user, format: :js, selected: @selected, prev_date: params[:start_date], dir: "backward"), method: :get, remote: true %>
  </div>

  <div id="next-month-button">
  <%= link_to '<i class="angle right icon"></i>'.html_safe, select_date_path(@user, format: :js, selected: @selected, prev_date: params[:start_date], dir: "forward"), method: :get, remote: true, id: "#next-month-button" %>
  </div>

  <%= month_calendar do |date| %>
    <br><%= date.day %><br>

    <% sum = 0 %>
    <% @attendance.each do |a| %>
      <% sum = sum + 1 if a.when.between?(date.beginning_of_day,date.end_of_day) %>
    <% end %>
    <% if sum == 0 %>
      <%= link_to " ", school_path(id: params[:selected], prev_date: params[:start_date], date: date, user: params[:id]), class: "ui massive red circular label" %>
    <% else %>
      <%= link_to sum, school_path(id: params[:selected], prev_date: params[:start_date], date: date, user: params[:id]), class: "ui massive blue circular label" %>
    <% end %>
  <% end %>

projects/OYD-Daily/OYD_Daily_App/app/views/users/_school_selector.html.erb
  
  <div class="ui selection dropdown">
	  <input type="hidden" name="School">
	  <i class="dropdown icon"></i>
	  <div class="default text"><%= @selected.school_name %></div>
	  <div class="menu" id="school-options">
		  <% @schools.each do |s| %>
		 
		      	
		      	<%= link_to select_school_path(@user, format: :js, selected: s, prev_date: params[:start_date]), method: :get, remote: true do %>
		      		<div class="item"><%= s.school_name%></div>
		      	<% end %>
	

		  <% end %>
	  </div>
  </div>

projects/OYD-Daily/OYD_Daily_App/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

projects/OYD-Daily/OYD_Daily_App/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Oyd</th>
      <th>Access level</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Def school</th>
      <th>Def region</th>
      <th>Def nat area</th>
      <th>Auth schools</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.oyd_id %></td>
        <td><%= user.access_level %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.def_school %></td>
        <td><%= user.def_region %></td>
        <td><%= user.def_nat_area %></td>
        <td><%= user.auth_schools %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

projects/OYD-Daily/OYD_Daily_App/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

projects/OYD-Daily/OYD_Daily_App/app/views/users/select_date.js.erb
$("#school-selector").html("<%= escape_javascript(render partial: 'school_selector')%>")
$("#month-data").html("<%= escape_javascript(render partial: 'month_data')%>")

$(function(){
        $('.ui.dropdown').dropdown();
})

projects/OYD-Daily/OYD_Daily_App/app/views/users/select_school.js.erb
$("#school-selector").html("<%= escape_javascript(render partial: 'school_selector')%>")
$("#month-data").html("<%= escape_javascript(render partial: 'month_data')%>")

$(function(){
        $('.ui.dropdown').dropdown();
})

projects/OYD-Daily/OYD_Daily_App/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div id="dashboard">

<div id="school-selector">
  <%= render partial: "school_selector" %>
</div>

<table id="monthly-stats">
    <tr>
      <th id="active">
        <div class="ui big label">
          <div class="detail">0</div>
        </div><br>
        ACTIVE 
      </th>
      <th>
        <div class="ui big label">
          <div class="detail">0</div>
        </div><br>
        ATTENDANCE
      </th>
      <th>
        <div class="ui big label">
          <div class="detail">0</div>
        </div><br>
        INFOS
      </th>
      <th>
        <div class="ui big label">
          <div class="detail">0</div>
        </div><br>
        NEW STUDENTS
      </th>
      <th>
        <div class="ui big label">
          <div class="detail">0</div>
        </div><br>
        NEW COURSES
      </th>
      <th>
        <div class="ui big label">
          <div class="detail">0</div>
        </div><br>
        TESTS
      </th>
      <th>
        <div class="ui big label">
          <div class="detail">0</div>
        </div><br>
        DROPS
      </th>
    </tr>
  </table>

 </div>

<br><br><br><br>
<div class="ui divider"></div>
<br><br>



<div id="month-data">
  <%= render partial: "month_data" %>

</div>

<br><br><br><br>
<%# link_to 'Edit', edit_user_path(@user) %> |
<%# link_to 'Back', users_path %>