projects/dispatch/config/routes.rb
Rails.application.routes.draw do
  resources :departments

  resources :responses

  resources :report_custom_comments

  resources :incident_report_comments

  resources :incident_question_custom_answers

  resources :incident_question_answers
  
  resources :incident_questions

  resources :incidents
  
  resources :users

  get 'sessions/new'

  get 'users/new'

  root 'sessions#new' #incidents#index'

  get '/api-docs', :to => redirect('/api.html')
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'incidents_questions/new/:type' => 'incidents_questions#new'

end

projects/dispatch/app/models/report_comment.rb
class ReportComment < ActiveRecord::Base
    belongs_to :incident
    belongs_to :incident_question_answer
    validates :incident, presence: true
    validates :incident_question_answer, presence: true

    # Method to use memcached, grab all incidents from cache, 
    # else execute code block which queries database for the,
    def self.all_cached
        Rails.cache.fetch('ReportComment.all') { all }
    end


    # Expire the cached 'all incidents' if a new incident was
    # saved or old incident was deleted
    after_save :expire_report_comment_all_cache
    after_save :expire_report_comment_all_cache
    def expire_report_comment_all_cache()
        Rails.cache.delete('ReportComment.all')
    end
    
 end

projects/dispatch/app/controllers/report_comments_controller.rb
class ReportCommentsController < ApplicationController
  before_action :authenticate
  before_action :set_report_comment, only: [:show, :edit, :update, :destroy]

  # GET /report_comments
  # GET /report_comments.json
  def index
    @report_comments = ReportComment.all
  end

  # GET /report_comments/1
  # GET /report_comments/1.json
  def show
  end

  # GET /report_comments/new
  def new
    @report_comment = ReportComment.new
  end

  # GET /report_comments/1/edit
  def edit
  end

  # POST /report_comments
  # POST /report_comments.json
  def create
    @report_comment = ReportComment.new(incident_report_comment_params)

    respond_to do |format|
      if @report_comment.save
        format.html { redirect_to @report_comment, notice: 'Report comment was successfully created.' }
        format.json { render :show, status: :created, location: @report_comment }
      else
        format.html { render :new }
        format.json { render json: @report_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /report_comments/1
  # PATCH/PUT /report_comments/1.json
  def update
    respond_to do |format|
      if @report_comment.update(incident_report_comment_params)
        format.html { redirect_to @report_comment, notice: 'Report comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @report_comment }
      else
        format.html { render :edit }
        format.json { render json: @report_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /report_comments/1
  # DELETE /report_comments/1.json
  def destroy
    @report_comment.destroy
    respond_to do |format|
      format.html { redirect_to report_comments_url, notice: 'Report comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report_comment
      @report_comment = ReportComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_comment_params
      params.require(:report_comment).permit(:incident_question_answer_id, :incident_id)
    end
end

projects/dispatch/app/views/report_comments/_form.html.erb
<%= simple_form_for(@report_comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :incident_question_answer %>
    <%= f.association :incident %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

projects/dispatch/app/views/report_comments/edit.html.erb
<h1>Editing Incident Report Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @report_comment %> |
<%= link_to 'Back', report_comments_path %>

projects/dispatch/app/views/report_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Incident Report Comments</h1>

<table>
  <thead>
    <tr>
      <th>Incident question answer</th>
      <th>Incident</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @report_comments.each do |report_comment| %>
      <tr>
        <td><%= report_comment.incident_question_answer %></td>
        <td><%= report_comment.incident %></td>
        <td><%= link_to 'Show', report_comment %></td>
        <td><%= link_to 'Edit', edit_report_comment_path(report_comment) %></td>
        <td><%= link_to 'Destroy', report_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Incident report comment', new_report_comment_path %>

projects/dispatch/app/views/report_comments/new.html.erb
<h1>New Incident Report Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', report_comments_path %>

projects/dispatch/app/views/report_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Incident question answer:</strong>
  <%= @report_comment.incident_question_answer %>
</p>

<p>
  <strong>Incident:</strong>
  <%= @report_comment.incident %>
</p>

<%= link_to 'Edit', edit_report_comment_path(@report_comment) %> |
<%= link_to 'Back', report_comments_path %>